### PR TITLE
A ton of mod compat and some vanilla recipes

### PR DESCRIPTION
**Pull request by ghost**
This PR introduces some compatibility with other mods.

The main reason I did this is because I use [Consistency+](https://modrinth.com/mod/consistencyplus), which introduces Cobbled variants for many variants of vanilla stone (netherrack, diorite, etc), and smelting it back into regular stone is tedious. The Kiln is perfect for this.

Then I got carried away and added support for a bunch of other mods in my pack.

Partial compatibility:
- Consistency+ (mostly just cobblestone -> stone recipes, this mod adds hundreds of smelting recipes and proper support would probably need dynamic recipe generation on their end...)

(Probably) full compatibility:
- AE2
- Biome Makeover
- Botania
- Oh The Biomes You'll Go
- Malum (Quilt)
- Paradise Lost
- Twigs

Vanilla stuff:
- Basalt, Blackstone and Deepslate recipes

### CODE REVIEW

**Comment by LemmaEOF** [comment]
Ooh, thank you so much! My one concern is that this is gonna cause a *lot* of logspam if someone doesn't have every single compatible mod included - I'll take a look into options with that at some point soon.

**Comment by goldenapple3** [comment]
Ah, right, I forgot that not everybody will be using my modpack, whoops.
I think I know a way to help with the spam.

**Comment by goldenapple3** [comment]
I've added conditional loading though have not tested it, the structure is copied from https://github.com/JieningYu/CreatePlus/blob/datapack/fabric/1.18.2/data/ae2/tags/items/metal_ingots.json and I do know that *that* works

**Comment by LemmaEOF** [comment]
LGTM! Thank you so much ^.^

**Pull request merged**
